app1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app1 import settings
from app1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns +=[
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create-order/', views.create_order, name='create_order'),
    path('download/<int:order_id>/', views.download_order_receipt, name='download_order_receipt'),
]

orders/models.py
from unicodedata import category
from django.db import models
from goods.models import Categories, Products

from users.models import User


class OrderitemQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    
    PRICE_MODEL_CHOICES = [
        ('CPC', 'За количество щелчков мышью(СPC)'),
        ('CPM', 'За количество показов(CPM)'),
        ('CPA', 'За количество действий(CPA)'),
    ]
    price_model = models.CharField(max_length=3, choices=PRICE_MODEL_CHOICES, verbose_name="Выбор ценовой модели")
    
    PAYMENT_ON_GET_CHOICES = [
        ('card', 'Карта'),
        ('ewallet', 'Электронные деньги'),
    ]
    
    payment_on_get = models.CharField(max_length=10, choices=PAYMENT_ON_GET_CHOICES, verbose_name="Способ оплаты")


    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")


    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.price, 2)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    price_model = forms.CharField()
    payment_on_get = forms.CharField()

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
        
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера")

        return data

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import redirect, render


from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem


@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # Создать заказ
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            price_model=form.cleaned_data['price_model'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )
                        # Создать заказанные товары
                        for cart_item in cart_items:
                            product=cart_item.product
                            name=cart_item.product.name
                            price=cart_item.product.price

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                            )
                            product.save()

                        # Очистить корзину пользователя после создания заказа
                        cart_items.delete()

                        messages.success(request, 'Заказ оформлен!')
                        return redirect('user:profile')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            }

        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'Home - Оформление заказа',
        'form': form,
        'orders': True,
    }
    return render(request, 'orders/create_order.html', context=context)




def download_order_receipt(request, order_id):
    order = Order.objects.get(pk=order_id)
    order_items = OrderItem.objects.filter(order=order)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="receipt_{order_id}.pdf"'

    doc = SimpleDocTemplate(response, pagesize=letter)
    elements = []

    # Регистрация шрифта с поддержкой кириллицы
    pdfmetrics.registerFont(TTFont('FreeSans', 'static/deps/font_text/FreeSans.ttf'))

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CustomHeading', fontName='FreeSans', fontSize=16, leading=20, alignment=1))
    styles.add(ParagraphStyle(name='CustomBodyText', fontName='FreeSans', fontSize=12, leading=14))

    elements.append(Paragraph(f'Чек заказа № {order.id}', styles['CustomHeading']))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(f'Имя: {order.user.first_name}', styles['CustomBodyText']))
    elements.append(Paragraph(f'Фамилия: {order.user.last_name}', styles['CustomBodyText']))
    elements.append(Spacer(1, 12))

    for item in order_items:
        elements.append(Paragraph(f'Товар: {item.name}', styles['CustomBodyText']))
        elements.append(Paragraph(f'Цена: {item.price}', styles['CustomBodyText']))
        elements.append(Paragraph(f'Время: {item.created_timestamp}', styles['CustomBodyText']))
        elements.append(Spacer(1, 6))

    elements.append(Paragraph(f'Ценовая модель: {order.price_model}', styles['CustomBodyText']))

    doc.build(elements)
    return response

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}


{% block content %}
<div class="col-lg-10">
    <!-- Контент на странице -->
    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <div class="container">
            <h3 class="text-center mb-4">Выбранные товары</h3>
            <div class="container" id="cart-items-container">
                <!-- Разметка корзины -->
                {% user_carts request as carts %}
                {% include "carts/includes/included_cart.html" %}
                <!-- Закончилась разметка корзины -->
            </div>
        </div>
        <!-- Детали заказа -->
        <div class="container">
            <h3 class="text-center">Детали заказа</h3>
            <div class="card mb-3">
                <div class="card-body">
                    <form action = "{% url "orders:create_order" %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*:</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                    name="first_name" required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*:</label>
                                <input type="text" class="form-control" id="id_last_name" name="last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                required>
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                    value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                    placeholder="В формате: XXX-XXX-XX-XX"
                                    required>
                                {% if form.phone_number.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="delivery" class="form-label">Выбор ценовой модели: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="price_model"
                                        id="id_price_model" value="CPM" checked>
                                    <label class="form-check-label" for="id_price_model">За количество показов(CPM)</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="price_model"
                                        id="id_price_model" value="CPC">
                                    <label class="form-check-label" for="id_price_model">За количество щелчков мышью(СPC)</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="price_model"
                                        id="id_price_model" value="CPA" checked>
                                    <label class="form-check-label" for="id_price_model">За количество действий(CPA)</label>
                                </div>
                            </div>
                            <div class="col-md-12 mb-3">
                                    <label class="form-label">Способ оплаты: </label>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="payment_on_get"
                                            id="id_payment_on_get" value="card" checked>
                                        <label class="form-check-label" for="id_payment_on_get">Оплата
                                            картой</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" name="payment_on_get"
                                            id="id_payment_on_get" value="ewallet">
                                        <label class="form-check-label" for="id_payment_on_get">Электронные деньги</label>
                                    {% if form.payment_on_get.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{form.payment_on_get.errors}}</div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark" >Оформить заказ</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>     


{% endblock content %}